### ISSUE TITLE
Exception: Failed to create virtualenv: /workspace/servo/target/debug/build/mozjs_sys-1352731da3144e78/out/_virtualenv

### ISSUE THREAD

**Issue by jankeromnes** [servo/mozjs#169]
Hello!

I tried creating 8 Servo workspaces on gitpod.io, and ran `./mach build -d` in all of them (for a stress test).

Most of these builds succeeded, but one of these (identical) builds failed with:

```
   Compiling mozjs_sys v0.61.6
   Compiling script v0.0.1 (/workspace/servo/components/script)
   Compiling compositing v0.0.1 (/workspace/servo/components/compositing)
   Compiling glutin v0.19.0
error: failed to run custom build command for `mozjs_sys v0.61.6`
process didn't exit successfully: `/workspace/servo/target/debug/build/mozjs_sys-c7ce3ec219d28561/build-script-build` (exit code: 101)
--- stdout
[[ /home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/js/src/configure -ot /home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/js/src/configure.in ]] && touch /home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/js/src/configure || true
[[ /home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/js/src/old-configure -ot /home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/js/src/old-configure.in ]] && touch /home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/js/src/old-configure || true
! [[ /home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/js/src/configure.in -ot /home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/js/src/configure ]] && touch /home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/js/src/configure || true
! [[ /home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/js/src/old-configure.in -ot /home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/js/src/old-configure ]] && touch /home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/js/src/old-configure || true
if [[ /home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/js/src/configure -nt /workspace/servo/target/debug/build/mozjs_sys-1352731da3144e78/out/config.status ]] ; then \
  cd /workspace/servo/target/debug/build/mozjs_sys-1352731da3144e78/out && \
  PYTHON="python2" MOZ_TOOLS="" \
  CC="gcc" CFLAGS="" \
  CPP="gcc -E" CPPFLAGS="" \
  CXX="g++" CXXFLAGS="" \
  AS="" AR="ar" \
  STLPORT_LIBS="" \
  /home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/js/src/configure --disable-jemalloc --disable-js-shell --disable-tests --build-backends=RecursiveMake --disable-shared-js || (cat config.log && exit 1) ; \
fi
Reexecuting in the virtualenv
Creating Python environment
Please use the *system* python to run this script
Traceback (most recent call last):
  File "/home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/third_party/python/virtualenv/virtualenv.py", line 2325,in <module>
    main()
  File "/home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/third_party/python/virtualenv/virtualenv.py", line 711, in main
    symlink=options.symlink and hasattr(os, 'symlink')) # MOZ: Make sure we don't use symlink when we don't have it
  File "/home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/third_party/python/virtualenv/virtualenv.py", line 924, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/workspace/servo/target/debug/build/mozjs_sys-1352731da3144e78/out/_virtualenv/lib/python2.7/posixpath.py", line 360, in abspath
    if not isabs(path):
  File "/workspace/servo/target/debug/build/mozjs_sys-1352731da3144e78/out/_virtualenv/lib/python2.7/posixpath.py", line 54, in isabs
    return s.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'
INFO: Creating Python environment
INFO: Please use the *system* python to run this script
INFO: Traceback (most recent call last):
INFO:   File "/home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/third_party/python/virtualenv/virtualenv.py", line2325, in <module>
INFO:     main()
INFO:   File "/home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/third_party/python/virtualenv/virtualenv.py", line711, in main
INFO:     symlink=options.symlink and hasattr(os, 'symlink')) # MOZ: Make sure we don't use symlink when we don't have it
INFO:   File "/home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/third_party/python/virtualenv/virtualenv.py", line924, in create_environment
INFO:     site_packages=site_packages, clear=clear, symlink=symlink))
INFO:   File "/workspace/servo/target/debug/build/mozjs_sys-1352731da3144e78/out/_virtualenv/lib/python2.7/posixpath.py", line 360, in abspath
INFO:     if not isabs(path):
INFO:   File "/workspace/servo/target/debug/build/mozjs_sys-1352731da3144e78/out/_virtualenv/lib/python2.7/posixpath.py", line 54, in isabs
INFO:     return s.startswith('/')
INFO: AttributeError: 'NoneType' object has no attribute 'startswith'

--- stderr
Traceback (most recent call last):
  File "/home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/js/src/../../configure.py", line 127, in <module>
    sys.exit(main(sys.argv))
  File "/home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/js/src/../../configure.py", line 29, in main
    sandbox.run(os.path.join(os.path.dirname(__file__), 'moz.configure'))
  File "/home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 399, in run
    self.include_file(path)
  File "/home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 390, in include_file
    exec_(code, self)
  File "/home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/python/mozbuild/mozbuild/util.py", line 59, in exec_
    exec(object, globals, locals)
  File "/home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/moz.configure", line 7, in <module>
    include('build/moz.configure/init.configure')
  File "/home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 694, in include_impl
    self.include_file(what)
  File "/home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 390, in include_file
    exec_(code, self)
  File "/home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/python/mozbuild/mozbuild/util.py", line 59, in exec_
    exec(object, globals, locals)
  File "/home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/build/moz.configure/init.configure", line 207, in <module>
    @imports('distutils.sysconfig')
  File "/home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 677, in decorator
    depends = DependsFunction(self, func, dependencies, when=when)
  File "/home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 96, in __init__
    sandbox._value_for(self)
  File "/home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 474, in _value_for
    return self._value_for_depends(obj, need_help_dependency)
  File "/home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/python/mozbuild/mozbuild/util.py", line 944, in method_call
    cache[args] = self.func(instance, *args)
  File "/home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 483, in _value_for_depends
    return obj.result(need_help_dependency)
  File "/home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/python/mozbuild/mozbuild/util.py", line 944, in method_call
    cache[args] = self.func(instance, *args)
  File "/home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 123, in result
    return self._func(*resolved_args)
  File "/home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 1003, in wrapped
    return new_func(*args, **kwargs)
  File "/home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/build/moz.configure/init.configure", line 255, in virtualenv_python
    manager.build(python)
  File "/home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/python/mozbuild/mozbuild/virtualenv.py", line 439, in build
    self.create(python)
  File "/home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/python/mozbuild/mozbuild/virtualenv.py", line 203, in create
    'Failed to create virtualenv: %s' % self.virtualenv_root)
Exception: Failed to create virtualenv: /workspace/servo/target/debug/build/mozjs_sys-1352731da3144e78/out/_virtualenv
make: *** [makefile.cargo:168: maybe-configure] Error 1
thread 'main' panicked at 'assertion failed: result.success()', /home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/build.rs:114:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
    Building [=================================================>     ] 530/576: mozangle(build)
error: build failed
[Warning] Could not generate notification! Optional Python module 'dbus' is not installed.
Build FAILED in 0:21:36
```

It's probably me (or gitpod.io's environment) doing something wrong, but I just thought I'd open an issue anyway in case it's useful.

Please feel free to close it if not.

**Comment by jdm** [comment]
I have also seen this occur on TravisCI. I'm not sure what to make of it.

**Comment by nox** [comment]
I found some issues:

https://github.com/platformio/platformio-atom-ide/issues/700
https://github.com/platformio/platformio-atom-ide/issues/455

**Comment by jschwe** [comment]
Closing as stale, I don't think this can still happen.
