### ISSUE TITLE
ImportError: No module named urllib3

### ISSUE THREAD

**Issue by paulrouget** [servo/mozjs#181]
I'm setting up a new Windows computer, and I'm running into this issue:

```
error: failed to run custom build command for `mozjs_sys v0.61.12`
process didn't exit successfully: `C:\Users\paul.DESKTOP-525R3BF\git\servo\target\debug\build\mozjs_sys-96ffa37950db32a9\build-script-build` (exit code: 101)
--- stdout
[[ /c/Users/paul.DESKTOP-525R3BF/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.12/mozjs/js/src/configure -ot /c/Users/paul.DESKTOP-525R3BF/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.12/mozjs/js/src/configure.in ]] && touch /c/Users/paul.DESKTOP-525R3BF/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.12/mozjs/js/src/configure || true
[[ /c/Users/paul.DESKTOP-525R3BF/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.12/mozjs/js/src/old-configure -ot /c/Users/paul.DESKTOP-525R3BF/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.12/mozjs/js/src/old-configure.in ]] && touch /c/Users/paul.DESKTOP-525R3BF/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.12/mozjs/js/src/old-configure || true
! [[ /c/Users/paul.DESKTOP-525R3BF/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.12/mozjs/js/src/configure.in -ot /c/Users/paul.DESKTOP-525R3BF/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.12/mozjs/js/src/configure ]] && touch /c/Users/paul.DESKTOP-525R3BF/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.12/mozjs/js/src/configure || true
! [[ /c/Users/paul.DESKTOP-525R3BF/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.12/mozjs/js/src/old-configure.in -ot /c/Users/paul.DESKTOP-525R3BF/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.12/mozjs/js/src/old-configure ]] && touch /c/Users/paul.DESKTOP-525R3BF/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.12/mozjs/js/src/old-configure || true
if [[ /c/Users/paul.DESKTOP-525R3BF/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.12/mozjs/js/src/configure -nt C:/Users/paul.DESKTOP-525R3BF/git/servo/target/debug/build/mozjs_sys-b084d8c01a39aee7/out/config.status ]] ; then \
  cd C:/Users/paul.DESKTOP-525R3BF/git/servo/target/debug/build/mozjs_sys-b084d8c01a39aee7/out && \
  PYTHON="C:\Python27\python.exe" MOZ_TOOLS="/" \
  CC="clang-cl.exe" CFLAGS="" \
  CPP="" CPPFLAGS="" \
  CXX="clang-cl.exe" CXXFLAGS="" \
  AS="" AR="" \
  STLPORT_LIBS="" \
  /c/Users/paul.DESKTOP-525R3BF/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.12/mozjs/js/src/configure --disable-jemalloc --disable-js-shell --disable-tests --disable-shared-js --build-backends=RecursiveMake --target=x86_64-pc-mingw32 --host=x86_64-pc-mingw32 --without-pthreads || (cat config.log && exit 1) ; \
fi
Creating Python environment
New python executable in c:\Users\paul.DESKTOP-525R3BF\git\servo\target\debug\build\mozjs_sys-b084d8c01a39aee7\out\_virtualenv\Scripts\python.exe
Installing setuptools, pip, wheel...
  Complete output from command c:\Users\paul.DESKTO...v\Scripts\python.exe - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "c:\Users\paul.DESKTOP-525R3BF\.cargo\registry\src\github.com-1ecc6299db9ec823\mozjs_sys-0.61.12\mozjs\third_party\python\virtualenv\virtualenv_support\pip-8.1.2-py2.py3-none-any.whl\pip\__init__.py", line 16, in <module>
  File "c:\Users\paul.DESKTOP-525R3BF\.cargo\registry\src\github.com-1ecc6299db9ec823\mozjs_sys-0.61.12\mozjs\third_party\python\virtualenv\virtualenv_support\pip-8.1.2-py2.py3-none-any.whl\pip\vcs\mercurial.py", line 9, in <module>
  File "c:\Users\paul.DESKTOP-525R3BF\.cargo\registry\src\github.com-1ecc6299db9ec823\mozjs_sys-0.61.12\mozjs\third_party\python\virtualenv\virtualenv_support\pip-8.1.2-py2.py3-none-any.whl\pip\download.py", line 39, in <module>
  File "c:\Users\paul.DESKTOP-525R3BF\.cargo\registry\src\github.com-1ecc6299db9ec823\mozjs_sys-0.61.12\mozjs\third_party\python\virtualenv\virtualenv_support\pip-8.1.2-py2.py3-none-any.whl\pip\_vendor\requests\__init__.py", line 61, in <module>
  File "c:\Users\paul.DESKTOP-525R3BF\.cargo\registry\src\github.com-1ecc6299db9ec823\mozjs_sys-0.61.12\mozjs\third_party\python\virtualenv\virtualenv_support\pip-8.1.2-py2.py3-none-any.whl\pip\_vendor\requests\packages\__init__.py", line 29, in <module>
ImportError: No module named urllib3
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "c:/Users/paul.DESKTOP-525R3BF/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.12/mozjs\third_party\python\virtualenv\virtualenv.py", line 2325, in <module>
    main()
  File "c:/Users/paul.DESKTOP-525R3BF/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.12/mozjs\third_party\python\virtualenv\virtualenv.py", line 711, in main
    symlink=options.symlink and hasattr(os, 'symlink')) # MOZ: Make sure we don't use symlink when we don't have it
  File "c:/Users/paul.DESKTOP-525R3BF/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.12/mozjs\third_party\python\virtualenv\virtualenv.py", line 944, in create_environment
    download=download,
  File "c:/Users/paul.DESKTOP-525R3BF/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.12/mozjs\third_party\python\virtualenv\virtualenv.py", line 900, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "c:/Users/paul.DESKTOP-525R3BF/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.12/mozjs\third_party\python\virtualenv\virtualenv.py", line 795, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command c:\Users\paul.DESKTO...v\Scripts\python.exe - setuptools pip wheel failed with error code 1
INFO: Creating Python environment
INFO: New python executable in c:\Users\paul.DESKTOP-525R3BF\git\servo\target\debug\build\mozjs_sys-b084d8c01a39aee7\out\_virtualenv\Scripts\python.exe
INFO: Installing setuptools, pip, wheel...
INFO:   Complete output from command c:\Users\paul.DESKTO...v\Scripts\python.exe - setuptools pip wheel:
INFO:   Traceback (most recent call last):
INFO:   File "<stdin>", line 7, in <module>
INFO:   File "c:\Users\paul.DESKTOP-525R3BF\.cargo\registry\src\github.com-1ecc6299db9ec823\mozjs_sys-0.61.12\mozjs\third_party\python\virtualenv\virtualenv_support\pip-8.1.2-py2.py3-none-any.whl\pip\__init__.py", line 16, in <module>
INFO:   File "c:\Users\paul.DESKTOP-525R3BF\.cargo\registry\src\github.com-1ecc6299db9ec823\mozjs_sys-0.61.12\mozjs\third_party\python\virtualenv\virtualenv_support\pip-8.1.2-py2.py3-none-any.whl\pip\vcs\mercurial.py", line 9, in <module>
INFO:   File "c:\Users\paul.DESKTOP-525R3BF\.cargo\registry\src\github.com-1ecc6299db9ec823\mozjs_sys-0.61.12\mozjs\third_party\python\virtualenv\virtualenv_support\pip-8.1.2-py2.py3-none-any.whl\pip\download.py", line 39, in <module>
INFO:   File "c:\Users\paul.DESKTOP-525R3BF\.cargo\registry\src\github.com-1ecc6299db9ec823\mozjs_sys-0.61.12\mozjs\third_party\python\virtualenv\virtualenv_support\pip-8.1.2-py2.py3-none-any.whl\pip\_vendor\requests\__init__.py", line 61, in <module>
INFO:   File "c:\Users\paul.DESKTOP-525R3BF\.cargo\registry\src\github.com-1ecc6299db9ec823\mozjs_sys-0.61.12\mozjs\third_party\python\virtualenv\virtualenv_support\pip-8.1.2-py2.py3-none-any.whl\pip\_vendor\requests\packages\__init__.py", line 29, in <module>
INFO: ImportError: No module named urllib3
INFO: ----------------------------------------
INFO: ...Installing setuptools, pip, wheel...done.
INFO: Traceback (most recent call last):
INFO:   File "c:/Users/paul.DESKTOP-525R3BF/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.12/mozjs\third_party\python\virtualenv\virtualenv.py", line 2325, in <module>
INFO:     main()
INFO:   File "c:/Users/paul.DESKTOP-525R3BF/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.12/mozjs\third_party\python\virtualenv\virtualenv.py", line 711, in main
INFO:     symlink=options.symlink and hasattr(os, 'symlink')) # MOZ: Make sure we don't use symlink when we don't have it
INFO:   File "c:/Users/paul.DESKTOP-525R3BF/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.12/mozjs\third_party\python\virtualenv\virtualenv.py", line 944, in create_environment
INFO:     download=download,
INFO:   File "c:/Users/paul.DESKTOP-525R3BF/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.12/mozjs\third_party\python\virtualenv\virtualenv.py", line 900, in install_wheel
INFO:     call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
INFO:   File "c:/Users/paul.DESKTOP-525R3BF/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.12/mozjs\third_party\python\virtualenv\virtualenv.py", line 795, in call_subprocess
INFO:     % (cmd_desc, proc.returncode))
INFO: OSError: Command c:\Users\paul.DESKTO...v\Scripts\python.exe - setuptools pip wheel failed with error code 1

--- stderr
which: python2.7: unknown command
Traceback (most recent call last):
  File "c:/Users/paul.DESKTOP-525R3BF/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.12/mozjs/js/src/../../configure.py", line 127, in <module>
    sys.exit(main(sys.argv))
  File "c:/Users/paul.DESKTOP-525R3BF/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.12/mozjs/js/src/../../configure.py", line 29, in main
    sandbox.run(os.path.join(os.path.dirname(__file__), 'moz.configure'))
  File "c:\Users\paul.DESKTOP-525R3BF\.cargo\registry\src\github.com-1ecc6299db9ec823\mozjs_sys-0.61.12\mozjs\python\mozbuild\mozbuild\configure\__init__.py", line 399, in run
    self.include_file(path)
  File "c:\Users\paul.DESKTOP-525R3BF\.cargo\registry\src\github.com-1ecc6299db9ec823\mozjs_sys-0.61.12\mozjs\python\mozbuild\mozbuild\configure\__init__.py", line 390, in include_file
    exec_(code, self)
  File "c:\Users\paul.DESKTOP-525R3BF\.cargo\registry\src\github.com-1ecc6299db9ec823\mozjs_sys-0.61.12\mozjs\python\mozbuild\mozbuild\util.py", line 59, in exec_
    exec(object, globals, locals)
  File "c:/Users/paul.DESKTOP-525R3BF/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.12/mozjs/moz.configure", line 7, in <module>
    include('build/moz.configure/init.configure')
  File "c:\Users\paul.DESKTOP-525R3BF\.cargo\registry\src\github.com-1ecc6299db9ec823\mozjs_sys-0.61.12\mozjs\python\mozbuild\mozbuild\configure\__init__.py", line 694, in include_impl
    self.include_file(what)
  File "c:\Users\paul.DESKTOP-525R3BF\.cargo\registry\src\github.com-1ecc6299db9ec823\mozjs_sys-0.61.12\mozjs\python\mozbuild\mozbuild\configure\__init__.py", line 390, in include_file
    exec_(code, self)
  File "c:\Users\paul.DESKTOP-525R3BF\.cargo\registry\src\github.com-1ecc6299db9ec823\mozjs_sys-0.61.12\mozjs\python\mozbuild\mozbuild\util.py", line 59, in exec_
    exec(object, globals, locals)
  File "c:/Users/paul.DESKTOP-525R3BF/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.12/mozjs/build/moz.configure/init.configure", line 207, in <module>
    @imports('distutils.sysconfig')
  File "c:\Users\paul.DESKTOP-525R3BF\.cargo\registry\src\github.com-1ecc6299db9ec823\mozjs_sys-0.61.12\mozjs\python\mozbuild\mozbuild\configure\__init__.py", line 677, in decorator
    depends = DependsFunction(self, func, dependencies, when=when)
  File "c:\Users\paul.DESKTOP-525R3BF\.cargo\registry\src\github.com-1ecc6299db9ec823\mozjs_sys-0.61.12\mozjs\python\mozbuild\mozbuild\configure\__init__.py", line 96, in __init__
    sandbox._value_for(self)
  File "c:\Users\paul.DESKTOP-525R3BF\.cargo\registry\src\github.com-1ecc6299db9ec823\mozjs_sys-0.61.12\mozjs\python\mozbuild\mozbuild\configure\__init__.py", line 474, in _value_for
    return self._value_for_depends(obj, need_help_dependency)
  File "c:\Users\paul.DESKTOP-525R3BF\.cargo\registry\src\github.com-1ecc6299db9ec823\mozjs_sys-0.61.12\mozjs\python\mozbuild\mozbuild\util.py", line 944, in method_call
    cache[args] = self.func(instance, *args)
  File "c:\Users\paul.DESKTOP-525R3BF\.cargo\registry\src\github.com-1ecc6299db9ec823\mozjs_sys-0.61.12\mozjs\python\mozbuild\mozbuild\configure\__init__.py", line 483, in _value_for_depends
    return obj.result(need_help_dependency)
  File "c:\Users\paul.DESKTOP-525R3BF\.cargo\registry\src\github.com-1ecc6299db9ec823\mozjs_sys-0.61.12\mozjs\python\mozbuild\mozbuild\util.py", line 944, in method_call
    cache[args] = self.func(instance, *args)
  File "c:\Users\paul.DESKTOP-525R3BF\.cargo\registry\src\github.com-1ecc6299db9ec823\mozjs_sys-0.61.12\mozjs\python\mozbuild\mozbuild\configure\__init__.py", line 123, in result
    return self._func(*resolved_args)
  File "c:\Users\paul.DESKTOP-525R3BF\.cargo\registry\src\github.com-1ecc6299db9ec823\mozjs_sys-0.61.12\mozjs\python\mozbuild\mozbuild\configure\__init__.py", line 1003, in wrapped
    return new_func(*args, **kwargs)
  File "c:/Users/paul.DESKTOP-525R3BF/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.12/mozjs/build/moz.configure/init.configure", line 255, in virtualenv_python
    manager.build(python)
  File "c:\Users\paul.DESKTOP-525R3BF\.cargo\registry\src\github.com-1ecc6299db9ec823\mozjs_sys-0.61.12\mozjs\python\mozbuild\mozbuild\virtualenv.py", line 439, in build
    self.create(python)
  File "c:\Users\paul.DESKTOP-525R3BF\.cargo\registry\src\github.com-1ecc6299db9ec823\mozjs_sys-0.61.12\mozjs\python\mozbuild\mozbuild\virtualenv.py", line 203, in create
    'Failed to create virtualenv: %s' % self.virtualenv_root)
Exception: Failed to create virtualenv: c:/Users/paul.DESKTOP-525R3BF/git/servo/target/debug/build/mozjs_sys-b084d8c01a39aee7/out\_virtualenv
mozmake: *** [makefile.cargo:183: maybe-configure] Error 1
thread 'main' panicked at 'assertion failed: result.success()', C:\Users\paul.DESKTOP-525R3BF\.cargo\registry\src\github.com-1ecc6299db9ec823\mozjs_sys-0.61.12\build.rs:142:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by Eijebong** [comment]
`which: python2.7: unknown command`

I'd say you need to install python 2.7 ?

**Comment by paulrouget** [comment]
> I'd say you need to install python 2.7 ?

It is installed. Alongside `virtualenv`. `mach` is running.

**Comment by paulrouget** [comment]
> <jdm> maybe http://nidkil.me/category/python/page/3/ ?

**Comment by paulrouget** [comment]
> Will try that :
> 
> > jdm: maybe http://nidkil.me/category/python/page/3/ ?

Doesn't help. The env variable was properly set.

**Comment by paulrouget** [comment]
I'm not sure what happened here, but I think that I some point I might have installed python packages via msys' python, or ran mach with msys' python, which messed up something. I aggressively deleted python/caches & co, clobbered, reinstalled python and virtualenv, and now it's working.
