### ISSUE TITLE
Ubuntu 18.04 build fails: check_spidermonkey_style.py

### ISSUE THREAD

**Issue by JordanMajd** [servo/mozjs#214]
Included `mozjs_sys` as a dependency in a rust project which caused `cargo build` to fail on `check_spidermonkey_style.py`, full log below. 

After lots of debugging on my dev system I decided to try to isolate the issue,

1. Spun up a shiny new Ubuntu 18.04 VPS
2. Hail Mary the MozJS + Servodependencies
```bash
sudo apt update
# mozjs deps
sudo apt install clang-6.0 autoconf2.13
# servo deps
sudo apt install git curl autoconf libx11-dev \
    libfreetype6-dev libgl1-mesa-dri libglib2.0-dev xorg-dev \
    gperf g++ build-essential cmake virtualenv python-pip \
    libssl-dev libbz2-dev liblzma-dev libosmesa6-dev libxmu6 libxmu-dev \
    libglu1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libdbus-1-dev \
    libharfbuzz-dev ccache clang libunwind-dev \
    libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev autoconf2.13
```
3.  Install rust:
```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
source $HOME/.cargo/env
```
4.  Create new project named rerpo: `cargo new repro --vcs none && cd repro`
5.  Add `mozjs_sys`  as dependency: `echo 'mozjs_sys = "0.67.1"' >> Cargo.toml`
6. Build  w/ backtrace enabled: `RUST_BACKTRACE=1 cargo build`

Here is the output from the build:

```bashnet@box:~/workspace/repro$ RUST_BACKTRACE=1 cargo build
   Compiling mozjs_sys v0.67.1
error: failed to run custom build command for `mozjs_sys v0.67.1`

Caused by:
  process didn't exit successfully: `/home/net/workspace/repro/target/debug/build/mozjs_sys-4eb212082c5f0f61/build-script-build` (exit code: 101)
--- stdout
[[ /home/net/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.67.1/mozjs/js/src/configure -ot /home/net/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.67.1/mozjs/js/src/configure.in ]] && touch /home/net/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.67.1/mozjs/js/src/configure || true
[[ /home/net/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.67.1/mozjs/js/src/old-configure -ot /home/net/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.67.1/mozjs/js/src/old-configure.in ]] && touch /home/net/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.67.1/mozjs/js/src/old-configure || true
! [[ /home/net/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.67.1/mozjs/js/src/configure.in -ot /home/net/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.67.1/mozjs/js/src/configure ]] && touch /home/net/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.67.1/mozjs/js/src/configure || true
! [[ /home/net/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.67.1/mozjs/js/src/old-configure.in -ot /home/net/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.67.1/mozjs/js/src/old-configure ]] && touch /home/net/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.67.1/mozjs/js/src/old-configure || true
if [[ /home/net/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.67.1/mozjs/js/src/configure -nt /home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/config.status ]] ; then \
  cd /home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out && \
  PYTHON="python2" MOZ_TOOLS="" \
  CC="gcc" CFLAGS="" \
  CPP="gcc -E" CPPFLAGS="" \
  CXX="g++" CXXFLAGS="" \
  AS="" AR="ar" \
  STLPORT_LIBS="" \
  RUST_TARGET="x86_64-unknown-linux-gnu" RUST_HOST="x86_64-unknown-linux-gnu" \
  /home/net/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.67.1/mozjs/js/src/configure --disable-jemalloc --disable-js-shell --disable-tests --disable-shared-js --build-backends=RecursiveMake --enable-posix-nspr-emulation --disable-shared-js || (cat config.log && exit 1) ; \
fi
cd /home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out && make -f Makefile
make[1]: Entering directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out'
make[2]: Entering directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out'
make recurse_pre-export
make[3]: Entering directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out'
/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/_virtualenvs/init/bin/python -m mozbuild.action.process_install_manifest --track install_dist_include.track dist/include _build_manifests/install/dist_include
/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/_virtualenvs/init/bin/python -m mozbuild.action.process_install_manifest --track install_dist_public.track dist/public _build_manifests/install/dist_public
Elapsed: 0.00s; From dist/public: Kept 0 existing; Added/updated 0; Removed 0 files and 0 directories.
/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/_virtualenvs/init/bin/python -m mozbuild.action.process_install_manifest --track install_dist_private.track dist/private _build_manifests/install/dist_private
Elapsed: 0.02s; From dist/include: Kept 382 existing; Added/updated 0; Removed 0 files and 0 directories.
/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/_virtualenvs/init/bin/python -m mozbuild.action.process_install_manifest --track install__tests.track _tests _build_manifests/install/_tests
Elapsed: 0.00s; From dist/private: Kept 0 existing; Added/updated 0; Removed 0 files and 0 directories.
/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/_virtualenvs/init/bin/python -m mozbuild.action.process_install_manifest --track install_dist_bin.track dist/bin _build_manifests/install/dist_bin
Elapsed: 0.04s; From _tests: Kept 356 existing; Added/updated 0; Removed 0 files and 0 directories.
Elapsed: 0.00s; From dist/bin: Kept 1 existing; Added/updated 0; Removed 0 files and 0 directories.
make[3]: Leaving directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out'
make[2]: Leaving directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out'
make[2]: Entering directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out'
make recurse_export
make[3]: Entering directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out'
make[4]: Entering directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/config'
make[4]: Nothing to be done for 'host'.
make[4]: Leaving directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/config'
make[4]: Entering directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/config'
make[4]: Nothing to be done for 'export'.
make[4]: Leaving directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/config'
make[4]: Entering directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/js/src'
make[4]: Nothing to be done for 'export'.
make[4]: Leaving directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/js/src'
make[4]: Entering directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/mozglue/build'
make[4]: Nothing to be done for 'export'.
make[4]: Leaving directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/mozglue/build'
make[4]: Entering directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/memory/build'
make[4]: Nothing to be done for 'export'.
make[4]: Leaving directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/memory/build'
make[4]: Entering directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/js/src/build'
make[4]: Nothing to be done for 'export'.
make[4]: Leaving directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/js/src/build'
make[4]: Entering directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/js/src/gc'
make[4]: Nothing to be done for 'export'.
make[4]: Leaving directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/js/src/gc'
make[4]: Entering directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/js/src/frontend'
make[4]: Nothing to be done for 'export'.
make[4]: Leaving directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/js/src/frontend'
make[4]: Entering directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/js/src/jit'
make[4]: Nothing to be done for 'export'.
make[4]: Leaving directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/js/src/jit'
make[3]: Leaving directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out'
make[2]: Leaving directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out'
make[2]: Entering directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out'
make recurse_compile
make[3]: Entering directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out'
make[4]: Entering directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/mfbt'
make[4]: Nothing to be done for 'target'.
make[4]: Leaving directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/mfbt'
make[4]: Entering directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/js/src/editline'
make[4]: Nothing to be done for 'target'.
make[4]: Leaving directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/js/src/editline'
make[4]: Entering directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/modules/fdlibm/src'
make[4]: Nothing to be done for 'target'.
make[4]: Leaving directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/modules/fdlibm/src'
make[4]: Entering directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/memory/mozalloc'
make[4]: Nothing to be done for 'target'.
make[4]: Leaving directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/memory/mozalloc'
make[4]: Entering directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/mozglue/misc'
make[4]: Nothing to be done for 'target'.
make[4]: Leaving directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/mozglue/misc'
make[4]: Entering directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/memory/build'
make[4]: Nothing to be done for 'target'.
make[4]: Leaving directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/memory/build'
make[4]: Entering directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/js/src/gc'
make[4]: Nothing to be done for 'target'.
make[4]: Leaving directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/js/src/gc'
make[4]: Entering directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/config/external/nspr'
make[4]: Nothing to be done for 'target'.
make[4]: Leaving directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/config/external/nspr'
make[4]: Entering directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/js/src'
make[4]: Nothing to be done for 'target'.
make[4]: Leaving directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/js/src'
make[4]: Entering directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/config/external/zlib'
make[4]: Nothing to be done for 'target'.
make[4]: Leaving directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/config/external/zlib'
make[4]: Entering directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/js/src/frontend'
make[4]: Nothing to be done for 'target'.
make[4]: Leaving directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/js/src/frontend'
make[4]: Entering directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/config/external/icu/data'
make[4]: Nothing to be done for 'target'.
make[4]: Leaving directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/config/external/icu/data'
make[4]: Entering directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/js/src/jit'
make[4]: Nothing to be done for 'target'.
make[4]: Leaving directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/js/src/jit'
make[4]: Entering directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/config/external/icu/common'
make[4]: Nothing to be done for 'target'.
make[4]: Leaving directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/config/external/icu/common'
make[4]: Entering directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/js/src/wasm'
make[4]: Nothing to be done for 'target'.
make[4]: Leaving directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/js/src/wasm'
make[4]: Entering directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/config'
make[4]: Nothing to be done for 'host'.
make[4]: Leaving directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/config'
make[4]: Entering directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/mozglue/build'
make[4]: Nothing to be done for 'target'.
make[4]: Leaving directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/mozglue/build'
make[4]: Entering directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/config/external/icu/i18n'
make[4]: Nothing to be done for 'target'.
make[4]: Leaving directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/config/external/icu/i18n'
make[4]: Entering directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/config/external/icu'
make[4]: Nothing to be done for 'target'.
make[4]: Leaving directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/config/external/icu'
make[4]: Entering directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/js/src/build'
make[4]: Nothing to be done for 'target'.
make[4]: Leaving directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/js/src/build'
make[3]: Leaving directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out'
make[2]: Leaving directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out'
make[2]: Entering directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out'
make recurse_misc
make[3]: Entering directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out'
make[4]: Entering directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/js/src/build'
js/src/build/spidermonkey_checks.stub
/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/_virtualenvs/init/bin/python -m mozbuild.action.file_generate /home/net/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.67.1/mozjs/config/run_spidermonkey_checks.py main spidermonkey_checks .deps/spidermonkey_checks.pp .deps/spidermonkey_checks.stub libjs_static.a /home/net/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.67.1/mozjs/config/check_spidermonkey_style.py /home/net/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.67.1/mozjs/config/check_macroassembler_style.py /home/net/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.67.1/mozjs/config/check_js_opcode.py
--- check_spidermonkey_style.py expected output
+++ check_spidermonkey_style.py actual output
@@ -1,56 +0,0 @@
-js/src/tests/style/BadIncludes.h:3: error:
-    the file includes itself
-
-js/src/tests/style/BadIncludes.h:6: error:
-    "BadIncludes2.h" is included using the wrong path;
-    did you forget a prefix, or is the file not yet committed?
-
-js/src/tests/style/BadIncludes.h:8: error:
-    <tests/style/BadIncludes2.h> should be included using
-    the #include "..." form
-
-js/src/tests/style/BadIncludes.h:10: error:
-    "stdio.h" is included using the wrong path;
-    did you forget a prefix, or is the file not yet committed?
-
-js/src/tests/style/BadIncludes2.h:1: error:
-    vanilla header includes an inline-header file "tests/style/BadIncludes2-inl.h"
-
-js/src/tests/style/BadIncludesOrder-inl.h:5:6: error:
-    "vm/JSScript-inl.h" should be included after "vm/Interpreter-inl.h"
-
-js/src/tests/style/BadIncludesOrder-inl.h:6:7: error:
-    "vm/Interpreter-inl.h" should be included after "js/Value.h"
-
-js/src/tests/style/BadIncludesOrder-inl.h:7:8: error:
-    "js/Value.h" should be included after "ds/LifoAlloc.h"
-
-js/src/tests/style/BadIncludesOrder-inl.h:8:9: error:
-    "ds/LifoAlloc.h" should be included after "jsapi.h"
-
-js/src/tests/style/BadIncludesOrder-inl.h:9:10: error:
-    "jsapi.h" should be included after <stdio.h>
-
-js/src/tests/style/BadIncludesOrder-inl.h:10:11: error:
-    <stdio.h> should be included after "mozilla/HashFunctions.h"
-
-js/src/tests/style/BadIncludesOrder-inl.h:28:29: error:
-    "vm/JSScript.h" should be included after "vm/JSFunction.h"
-
-(multiple files): error:
-    header files form one or more cycles
-
-   tests/style/HeaderCycleA1.h
-   -> tests/style/HeaderCycleA2.h
-      -> tests/style/HeaderCycleA3.h
-         -> tests/style/HeaderCycleA1.h
-
-   tests/style/HeaderCycleB1-inl.h
-   -> tests/style/HeaderCycleB2-inl.h
-      -> tests/style/HeaderCycleB3-inl.h
-         -> tests/style/HeaderCycleB4-inl.h
-            -> tests/style/HeaderCycleB1-inl.h
-            -> tests/style/jsheadercycleB5inlines.h
-               -> tests/style/HeaderCycleB1-inl.h
-      -> tests/style/HeaderCycleB4-inl.h
-
TEST-UNEXPECTED-FAIL | check_spidermonkey_style.py | actual output does not match expected output;  diff is above.
TEST-UNEXPECTED-FAIL | check_spidermonkey_style.py | Hint: If the problem is that you renamed a header, and many #includes are no longer in alphabetical order, commit your work and then try `check_spidermonkey_style.py --fixup`. You need to commit first because --fixup modifies your files in place.
backend.mk:10: recipe for target '.deps/spidermonkey_checks.stub' failed
make[4]: Leaving directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out/js/src/build'
/home/net/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.67.1/mozjs/config/recurse.mk:101: recipe for target 'js/src/build/misc' failed
make[3]: Leaving directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out'
/home/net/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.67.1/mozjs/config/recurse.mk:32: recipe for target 'misc' failed
make[2]: Leaving directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out'
/home/net/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.67.1/mozjs/config/rules.mk:400: recipe for target 'default' failed
make[1]: Leaving directory '/home/net/workspace/repro/target/debug/build/mozjs_sys-bdee6ade2083da50/out'
makefile.cargo:184: recipe for target 'all' failed

--- stderr
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/net/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.67.1/mozjs/python/mozbuild/mozbuild/action/file_generate.py", line 120, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/net/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.67.1/mozjs/python/mozbuild/mozbuild/action/file_generate.py", line 71, in main
    ret = module.__dict__[method](output, *args.additional_arguments, **kwargs)
  File "/home/net/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.67.1/mozjs/config/run_spidermonkey_checks.py", line 15, in main
    raise Exception(script + " failed")
Exception: /home/net/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.67.1/mozjs/config/check_spidermonkey_style.py failed
make[4]: *** [.deps/spidermonkey_checks.stub] Error 1
make[3]: *** [js/src/build/misc] Error 2
make[2]: *** [misc] Error 2
make[1]: *** [default] Error 2
make: *** [all] Error 2
thread 'main' panicked at 'assertion failed: result.success()', /home/net/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.67.1/build.rs:111:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::begin_panic
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/panicking.rs:411
   8: build_script_build::build_jsapi
             at ./build.rs:111
   9: build_script_build::main
             at ./build.rs:16
  10: std::rt::lang_start::{{closure}}
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/rt.rs:64
  11: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  12: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  13: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  14: std::panicking::try
             at src/libstd/panicking.rs:275
  15: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  16: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  17: std::rt::lang_start
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/rt.rs:64
  18: main
  19: __libc_start_main
  20: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by jdm** [comment]
We are no longer able to publish new versions of mozjs_sys (and transitively mozjs) on crates.io, so please try using a git dependency instead.

**Comment by JordanMajd** [comment]
Thank you, that resolved my issue.

For posterity, my working `Cargo.toml`:

```
[package]
name = "repro"
version = "0.1.0"
edition = "2018"
[dependencies]
mozjs_sys = { git = "https://github.com/servo/mozjs.git" }
```
