### ISSUE TITLE
Fix build on windows when servo is located on a different drive than C:\

### ISSUE THREAD

**Issue by MeFisto94** [servo/mozjs#217]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1604667 for the background on this.
Short form:
```
Traceback (most recent call last):
  File "c:/Users/Marc/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/5906588/mozjs/js/src/../../configure.py", line 132, in <module>
    sys.exit(main(sys.argv))
  File "c:/Users/Marc/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/5906588/mozjs/js/src/../../configure.py", line 43, in main
    return config_status(config)
  File "c:/Users/Marc/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/5906588/mozjs/js/src/../../configure.py", line 127, in config_status
    return config_status(args=[], **encode(sanitized_config, encoding))
  File "c:\Users\Marc\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\5906588\mozjs\python\mozbuild\mozbuild\config_status.py", line 146, in config_status
    the_backend.consume(definitions)
  File "c:\Users\Marc\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\5906588\mozjs\python\mozbuild\mozbuild\backend\base.py", line 128, in consume
    if (not self.consume_object(obj) and
  File "c:\Users\Marc\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\5906588\mozjs\python\mozbuild\mozbuild\backend\recursivemake.py", line 438, in consume_object
    consumed = CommonBackend.consume_object(self, obj)
  File "c:\Users\Marc\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\5906588\mozjs\python\mozbuild\mozbuild\backend\common.py", line 134, in consume_object
    with self._get_preprocessor(obj) as pp:
  File "e:\mozilla-build\python\Lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "c:\Users\Marc\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\5906588\mozjs\python\mozbuild\mozbuild\backend\base.py", line 320, in _get_preprocessor
    srcdir_rel=mozpath.relpath(srcdir, mozpath.dirname(obj.output_path)),
  File "c:\Users\Marc\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\5906588\mozjs\python\mozbuild\mozpack\path.py", line 33, in relpath
    rel = normsep(os.path.relpath(path, start))
  File "e:\Marc\Documents\Coding\servo\target\debug\build\mozjs_sys-88004c1deb65babf\out\_virtualenvs\init\lib\ntpath.py", line 529, in relpath
    % (path_prefix, start_prefix))
ValueError: path is on drive c:, start on drive e:
```

I think we could detect this case `(if os == "windows" && getdrive(cargo) != getdrive(this))` and either symlink or copy the sources into a subfolder of the current servo folder (topsrcdir).

I wonder if [OUT_DIR](https://github.com/servo/mozjs/blob/618398c43fe9ec2a471687a243808a399f077d2a/build.rs#L53) isn't already enough for that? 
I tried to specify it on the command line, but I'm 99% sure it got swallowed by mach.

Apart from that, it would be great if this would automatically work in those cases as technically speaking there is no real reason the code has to be in CARGO_HOME, I assume, _as long as we manage to keep the local copy in sync_.

For now I'm going to live with the workaround, freeing space on the SSD, which has the nice side effect of a much better build speed and git performance, but ultimatively this is something that _could_ be fixed.

**Comment by sagudev** [comment]
I think this was fixed upstream in https://bugzilla.mozilla.org/show_bug.cgi?id=1604667.

Also servo used to be build on D in CI, but now only it's source reside on D drive it's target is now on C drive.
