### ISSUE TITLE
Building on Ubuntu 14.04.3 errors out

### ISSUE THREAD

**Issue by poppingtonic** [servo/mozjs#66]
``` bash
Failed to run custom build command for `mozjs_sys v0.0.0 (https://github.com/servo/mozjs#10796a16)`
Process didn't exit successfully: `/home/brian/git/servo/servo/target/debug/build/mozjs_sys-e411d274df144795/build-script-build` (exit code: 101)
--- stdout
cd /home/brian/git/servo/servo/target/debug/build/mozjs_sys-e411d274df144795/out && \
        MOZ_TOOLS="" CC="gcc" CPP="gcc -E" CXX="g++" AR="ar" \
        /home/brian/git/servo/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/configure --enable-gczeal --disable-jemalloc
creating cache ./config.cache
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking build system type... x86_64-unknown-linux-gnu
checking for gawk... no
checking for mawk... mawk
checking for perl5... no
checking for perl... /usr/bin/perl
checking for gcc... gcc
checking whether the C compiler (gcc  ) works... yes
checking whether the C compiler (gcc  ) is a cross-compiler... no
checking whether we are using GNU C... yes
checking whether gcc accepts -g... yes
checking for c++... g++
checking whether the C++ compiler (g++  ) works... yes
checking whether the C++ compiler (g++  ) is a cross-compiler... no
checking whether we are using GNU C++... yes
checking whether g++ accepts -g... yes
checking for ranlib... ranlib
checking for as... /usr/bin/as
checking for ar... ar
checking for ld... ld
checking for strip... strip
checking for windres... no
checking how to run the C preprocessor... gcc -E
checking how to run the C++ preprocessor... g++ -E
checking for sb-conf... no
checking for ve... no
checking for a BSD compatible install... /usr/bin/install -c
checking whether ln -s works... yes
checking for tar archiver... checking for gnutar... no
checking for gtar... no
checking for tar... tar
tar
checking for minimum required perl version >= 5.006... 5.018002
checking for full perl installation... yes
checking for python2.7... /home/brian/git/servo/servo/python/_virtualenv/bin/python2.7
Creating Python environment
Using real prefix '/usr'
  Cannot find file /home/brian/git/servo/servo/python/_virtualenv/lib/python2.7/config (bad symlink)
  Cannot find file /home/brian/git/servo/servo/python/_virtualenv/lib/python2.7/lib-dynload (bad symlink)
New python executable in /home/brian/git/servo/servo/target/debug/build/mozjs_sys-e411d274df144795/out/_virtualenv/bin/python2.7
Also creating executable in /home/brian/git/servo/servo/target/debug/build/mozjs_sys-e411d274df144795/out/_virtualenv/bin/python
Installing setuptools, pip...
  Complete output from command /home/brian/git/serv...ualenv/bin/python2.7 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip:
  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/brian/git/servo/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/python/virtualenv/virtualenv_support/pip-6.0.6-py2.py3-none-any.whl/pip/__init__.py", line 13, in <module>
  File "/home/brian/git/servo/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/python/virtualenv/virtualenv_support/pip-6.0.6-py2.py3-none-any.whl/pip/utils/__init__.py", line 22, in <module>
  File "/home/brian/git/servo/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/python/virtualenv/virtualenv_support/pip-6.0.6-py2.py3-none-any.whl/pip/_vendor/__init__.py", line 81, in load_module
ImportError: No module named 'pip._vendor.pkg_resources'
----------------------------------------
...Installing setuptools, pip...done.
Traceback (most recent call last):
  File "/home/brian/git/servo/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/python/virtualenv/virtualenv.py", line 2352, in <module>
    main()
  File "/home/brian/git/servo/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/python/virtualenv/virtualenv.py", line 825, in main
    symlink=options.symlink)
  File "/home/brian/git/servo/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/python/virtualenv/virtualenv.py", line 993, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "/home/brian/git/servo/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/python/virtualenv/virtualenv.py", line 961, in install_wheel
    'PIP_NO_INDEX': '1'
  File "/home/brian/git/servo/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/python/virtualenv/virtualenv.py", line 903, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/brian/git/serv...ualenv/bin/python2.7 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip failed with error code 1
------ config.log ------
configure:3049: checking whether g++ accepts -g
configure:3098: gcc -c   conftest.c 1>&5
configure:3115: gcc -c   conftest.c 1>&5
configure: In function 'main':
configure:3111:1: warning: incompatible implicit declaration of built-in function 'exit' [enabled by default]
configure:3134: checking for ranlib
configure:3166: checking for as
configure:3220: checking for ar
configure:3255: checking for ld
configure:3290: checking for strip
configure:3325: checking for windres
configure:3941: checking how to run the C preprocessor
configure:4021: checking how to run the C++ preprocessor
configure:4039: g++ -E  conftest.C >/dev/null 2>conftest.out
configure:4161: checking for sb-conf
configure:4161: checking for ve
configure:4223: checking for a BSD compatible install
configure:4276: checking whether ln -s works
configure:4298: checking for tar archiver
configure:4304: checking for gnutar
configure:4304: checking for gtar
configure:4304: checking for tar
configure:4341: checking for minimum required perl version >= 5.006
configure:4351: checking for full perl installation
configure:4369: checking for python2.7

--- stderr
makefile.cargo:58: Extraneous text after `else' directive
/home/brian/git/servo/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/configure: 1: /home/brian/git/servo/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/configure: /home/brian/git/servo/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/../../python/mozbuild/mozbuild/milestone.py: Permission denied
/home/brian/git/servo/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/configure: 1: /home/brian/git/servo/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/configure: /home/brian/git/servo/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/../../python/mozbuild/mozbuild/milestone.py: Permission denied
/home/brian/git/servo/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/configure: 1: /home/brian/git/servo/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/configure: /home/brian/git/servo/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/../../python/mozbuild/mozbuild/milestone.py: Permission denied
Traceback (most recent call last):
  File "/home/brian/git/servo/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/python/mozbuild/mozbuild/virtualenv.py", line 475, in <module>
    manager.ensure()
  File "/home/brian/git/servo/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/python/mozbuild/mozbuild/virtualenv.py", line 128, in ensure
    return self.build()
  File "/home/brian/git/servo/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/python/mozbuild/mozbuild/virtualenv.py", line 371, in build
    self.create()
  File "/home/brian/git/servo/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/python/mozbuild/mozbuild/virtualenv.py", line 147, in create
    raise Exception('Error creating virtualenv.')
Exception: Error creating virtualenv.
make: *** [all] Error 1
thread '<main>' panicked at 'assertion failed: result.success()', /home/brian/git/servo/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/build.rs:17

[Warning] Could not generate notification! Optional Python module 'dbus' is not installed.
Build completed in 1064.30s
```

**Comment by poppingtonic** [comment]
Command: `./mach build --dev` on a fresh clone of [servo](https://github.com/servo/servo)

**Comment by eefriedman** [comment]
We generally prefer bug reports to be filed against servo/servo.

Building servo works fine on my Ubuntu 14.04 install; are you sure you have all the right packages installed?  See https://github.com/servo/servo/blob/master/README.md .

**Comment by jdm** [comment]
Presumably it's the python2.7 virtualenv that's causing problems here, given this output:
```
hecking for python2.7... /home/brian/git/servo/servo/python/_virtualenv/bin/python2.7
Creating Python environment
Using real prefix '/usr'
  Cannot find file /home/brian/git/servo/servo/python/_virtualenv/lib/python2.7/config (bad symlink)
  Cannot find file /home/brian/git/servo/servo/python/_virtualenv/lib/python2.7/lib-dynload (bad symlink)
New python executable in /home/brian/git/servo/servo/target/debug/build/mozjs_sys-e411d274df144795/out/_virtualenv/bin/python2.7
Also creating executable in /home/brian/git/servo/servo/target/debug/build/mozjs_sys-e411d274df144795/out/_virtualenv/bin/python
Installing setuptools, pip...
  Complete output from command /home/brian/git/serv...ualenv/bin/python2.7 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip:
  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/brian/git/servo/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/python/virtualenv/virtualenv_support/pip-6.0.6-py2.py3-none-any.whl/pip/__init__.py", line 13, in <module>
  File "/home/brian/git/servo/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/python/virtualenv/virtualenv_support/pip-6.0.6-py2.py3-none-any.whl/pip/utils/__init__.py", line 22, in <module>
  File "/home/brian/git/servo/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/python/virtualenv/virtualenv_support/pip-6.0.6-py2.py3-none-any.whl/pip/_vendor/__init__.py", line 81, in load_module
ImportError: No module named 'pip._vendor.pkg_resources'
----------------------------------------
...Installing setuptools, pip...done.
Traceback (most recent call last):
  File "/home/brian/git/servo/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/python/virtualenv/virtualenv.py", line 2352, in <module>
    main()
  File "/home/brian/git/servo/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/python/virtualenv/virtualenv.py", line 825, in main
    symlink=options.symlink)
  File "/home/brian/git/servo/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/python/virtualenv/virtualenv.py", line 993, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "/home/brian/git/servo/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/python/virtualenv/virtualenv.py", line 961, in install_wheel
    'PIP_NO_INDEX': '1'
  File "/home/brian/git/servo/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/python/virtualenv/virtualenv.py", line 903, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/brian/git/serv...ualenv/bin/python2.7 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip failed with error code 1
```

**Comment by nox** [comment]
4 years old issue, closing.
