### ISSUE TITLE
Build failure on OS X El Capitan

### ISSUE THREAD

**Issue by AntoineRondelet** [servo/mozjs#76]
When I try to build on OS X El Capitan I get an error as shown below :
Any help would be welcomed.

```
arondele-hz-0:servo AntoineRondelet$ ./mach build -d
   Compiling mozjs_sys v0.0.0 (https://github.com/servo/mozjs#5ac99916)
error: failed to run custom build command for `mozjs_sys v0.0.0 (https://github.com/servo/mozjs#5ac99916)`
Process didn't exit successfully: `/Users/AntoineRondelet/Documents/Servo_project/servo/target/debug/build/mozjs_sys-736cac28b49f9dab/build-script-build` (exit code: 101)
--- stdout
cd /Users/AntoineRondelet/Documents/Servo_project/servo/target/debug/build/mozjs_sys-736cac28b49f9dab/out && \
    MOZ_TOOLS="" CC="gcc" CPP="gcc -E" CXX="g++" AR="ar" \
    /Users/AntoineRondelet/Documents/Servo_project/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/configure --disable-jemalloc
loading cache ./config.cache
checking host system type... x86_64-apple-darwin15.3.0
checking target system type... x86_64-apple-darwin15.3.0
checking build system type... x86_64-apple-darwin15.3.0
checking for mawk... (cached) awk
checking for perl5... (cached) /usr/bin/perl
checking for gcc... (cached) gcc
checking whether the C compiler (gcc  ) works... yes
checking whether the C compiler (gcc  ) is a cross-compiler... no
checking whether we are using GNU C... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for c++... (cached) g++
checking whether the C++ compiler (g++  ) works... yes
checking whether the C++ compiler (g++  ) is a cross-compiler... no
checking whether we are using GNU C++... (cached) yes
checking whether g++ accepts -g... (cached) yes
checking for ranlib... (cached) ranlib
checking for as... (cached) /usr/bin/as
checking for ar... (cached) ar
checking for ld... (cached) ld
checking for strip... (cached) strip
checking for windres... no
checking how to run the C preprocessor... gcc -E
checking how to run the C++ preprocessor... (cached) g++ -E
checking for sb-conf... no
checking for ve... no
checking for a BSD compatible install... (cached) /usr/bin/install -c
checking whether ln -s works... (cached) yes
checking for tar archiver... checking for gnutar... (cached) tar
tar
checking for minimum required perl version >= 5.006... 5.018002
checking for full perl installation... yes
checking for python2.7... (cached) /Users/AntoineRondelet/Documents/Servo_project/servo/python/_virtualenv/bin/python2.7
Creating Python environment
checking Python environment is Mozilla virtualenv... yes
checking for doxygen... (cached) :
checking for autoconf... (cached) /usr/local/bin/autoconf
checking for xargs... (cached) /usr/bin/xargs
checking for gmake... (cached) /usr/bin/make
checking for X... (cached) no
checking that static assertion macros used in autoconf tests work... (cached) yes
checking for --noexecstack option to as... yes
checking for -z noexecstack option to ld... no
checking for -z text option to ld... no
checking for --build-id option to ld... no
checking whether the C++ compiler supports -Wno-extended-offsetof... yes
checking whether ld has archive extraction flags... (cached) no
checking for 64-bit OS... yes
checking for -framework ExceptionHandling... yes
checking for -dead_strip option to ld... yes
checking whether the C++ compiler (g++  -fno-common -fno-rtti  -lobjc) actually is a C++ compiler... yes
checking for ANSI C header files... (cached) yes
checking for working const... (cached) yes
checking for mode_t... (cached) yes
checking for off_t... (cached) yes
checking for pid_t... (cached) yes
checking for size_t... (cached) yes
checking for ssize_t... (cached) yes
checking for endian.h... (cached) no
checking for machine/endian.h... (cached) yes
checking for sys/isa_defs.h... (cached) no
checking for gcc c++0x headers bug without rtti... (cached) no
checking for gcc PR49911... no
checking for llvm pr8927... no
checking for dirent.h that defines DIR... (cached) yes
checking for opendir in -ldir... (cached) no
checking for sys/byteorder.h... (cached) no
checking for compat.h... (cached) no
checking for getopt.h... (cached) yes
checking for sys/bitypes.h... (cached) no
checking for memory.h... (cached) yes
checking for unistd.h... (cached) yes
checking for gnu/libc-version.h... (cached) no
checking for nl_types.h... (cached) yes
checking for malloc.h... (cached) no
checking for X11/XKBlib.h... (cached) no
checking for io.h... (cached) no
checking for cpuid.h... (cached) yes
checking for sys/statvfs.h... (cached) yes
checking for sys/statfs.h... (cached) no
checking for sys/vfs.h... (cached) no
checking for sys/mount.h... (cached) yes
checking for sys/quota.h... (cached) no
checking for linux/quota.h... (cached) no
checking for sys/cdefs.h... (cached) yes
checking for linux/perf_event.h... (cached) no
checking for gethostbyname_r in -lc_r... (cached) no
checking for socket in -lsocket... (cached) no
checking whether gcc accepts -pthread... yes
checking whether gcc needs -traditional... (cached) no
checking for 8-bit clean memcmp... (cached) yes
checking for getc_unlocked... (cached) yes
checking for _getc_nolock... (cached) no
checking for gmtime_r... (cached) yes
checking for localtime_r... (cached) yes
checking for sin in -lm... (cached) yes
checking for log2... (cached) yes
checking for log1p... (cached) yes
checking for expm1... (cached) yes
checking for sqrt1pm1... (cached) no
checking for acosh... (cached) yes
checking for asinh... (cached) yes
checking for atanh... (cached) yes
checking for trunc... (cached) yes
checking for cbrt... (cached) yes
checking for wcrtomb... (cached) yes
checking for mbrtowc... (cached) yes
checking for res_ninit()... (cached) no
checking for nl_langinfo and CODESET... (cached) yes
checking for an implementation of va_copy()... (cached) yes
checking whether va_list can be copied by value... (cached) no
checking whether the C++ "using" keyword resolves ambiguity... (cached) yes
checking for C++ dynamic_cast to void*... (cached) yes
checking for __thread keyword for TLS variables... (cached) no
checking for __attribute__((always_inline))... (cached) yes
checking for __attribute__((malloc))... (cached) yes
checking for __attribute__((warn_unused_result))... (cached) yes
checking for LC_MESSAGES... (cached) yes
checking for localeconv... (cached) yes
checking NSPR selection... posix-wrapper
checking for gzread in -lz... (cached) yes
checking for valid optimization flags... yes
checking for __cxa_demangle... (cached) yes
checking for -pipe support... yes
checking whether C compiler supports -fprofile-generate... yes
checking for tm_zone tm_gmtoff in struct tm... (cached) yes
checking what kind of list files are supported by the linker... filelist
checking for posix_fadvise... (cached) no
checking for posix_fallocate... (cached) no
checking for malloc.h... (cached) no
checking for malloc_np.h... (cached) no
checking for malloc/malloc.h... (cached) yes
checking for setlocale... (cached) yes
checking for localeconv... (cached) yes
checking for malloc_size... (cached) yes
checking for malloc_usable_size... (cached) no
creating ./config.status

--- stderr
makefile.cargo:58: Extraneous text after `else' directive
/Users/AntoineRondelet/Documents/Servo_project/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/configure: line 1665: /Users/AntoineRondelet/Documents/Servo_project/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/../../python/mozbuild/mozbuild/milestone.py: Permission denied
/Users/AntoineRondelet/Documents/Servo_project/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/configure: line 1666: /Users/AntoineRondelet/Documents/Servo_project/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/../../python/mozbuild/mozbuild/milestone.py: Permission denied
/Users/AntoineRondelet/Documents/Servo_project/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/configure: line 1667: /Users/AntoineRondelet/Documents/Servo_project/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/../../python/mozbuild/mozbuild/milestone.py: Permission denied
Traceback (most recent call last):
  File "/Users/AntoineRondelet/Documents/Servo_project/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/build/subconfigure.py", line 422, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/Users/AntoineRondelet/Documents/Servo_project/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/build/subconfigure.py", line 406, in main
    return subconfigure(args)
  File "/Users/AntoineRondelet/Documents/Servo_project/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/build/subconfigure.py", line 393, in subconfigure
    pool.imap_unordered(run, subconfigures):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 668, in next
    raise value
IOError: [Errno 2] No such file or directory: 'intl/icu/target/tools/tzcode/Makefile'
make: *** [all] Error 1
thread '<main>' panicked at 'assertion failed: result.success()', /Users/AntoineRondelet/Documents/Servo_project/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/build.rs:17
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Build completed in 7.75s
```

**Comment by jdm** [comment]
Hmm, not sure why this is happening, but you can probably work around it by adding `--without-intl-api` to the `CONFIGURE_FLAGS` in `makefile.cargo`.

**Comment by AntoineRondelet** [comment]
``--without-intl-api`` was already written in ``makefile.cargo``
I tried to erase it for a test.  It doesn't work either...

**Comment by AntoineRondelet** [comment]
Perfect ! I added ``--without-intl-api`` to the first ``CONFIGURE_FLAGS`` and it works. Thank you very much for your help !

**Comment by jdm** [comment]
This was fixed by modifying the source, so let's not close it yet.

**Comment by nox** [comment]
The only place we disable intl now is UWP builds, so I don't think this issue is relevant anymore.
