### ISSUE TITLE
Add-missing-MOZ_ANDROID_CPU_ARCH-call-in-SpiderMonke.patch no longer applies on latest m-c

### ISSUE THREAD

**Issue by fitzgen** [servo/mozjs#92]
On m-c commit a70835fe9f55, the patch no longer applies.

``` shell
$ python3 ./etc/update.py ~/scratch/mozjs-51.0a1.0.tar.bz2
python3 ./etc/update.py ~/scratch/mozjs-51.0a1.0.tar.bz2
Extracting tarball.
Applying patches.
  Applying patch: /Users/fitzgen/src/mozjs/etc/patches/Add-WinNSPR.cpp-implementation.patch.
  Applying patch: /Users/fitzgen/src/mozjs/etc/patches/Add-missing-MOZ_ANDROID_CPU_ARCH-call-in-SpiderMonke.patch.
error: patch failed: mozjs/js/src/old-configure.in:584
error: mozjs/js/src/old-configure.in: patch does not apply
Traceback (most recent call last):
  File "./etc/update.py", line 70, in <module>
    main(sys.argv[1:])
  File "./etc/update.py", line 65, in main
    apply_patches()
  File "./etc/update.py", line 47, in apply_patches
    subprocess.check_call(["git", "am", p], stdout=subprocess.DEVNULL)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'am', '/Users/fitzgen/src/mozjs/etc/patches/Add-missing-MOZ_ANDROID_CPU_ARCH-call-in-SpiderMonke.patch']' returned non-zero exit status 128
```

**Comment by fitzgen** [comment]
I think this patch has been upstreamed.

**Comment by nox** [comment]
This patch is no more.
